first try
DGlobus/baseballCards pull request #1
Opened 2022-05-18 04:36 UTC by DGlobus

2022-05-18 10:10 UTC, mv-shallow requested changes

2022-05-18 10:10 UTC, mv-shallow commented on src/com/dasha/getCards/GetCardsFromTxt.java
> +        try{
Правильнее будет вынести создание File за пределы try-catch, а создание FileReader и BufferedReader внести в try() следующим образом:         
File file = new File(path);
        try (FileReader fileReader = new FileReader(file);
             BufferedReader bufferedReader = new BufferedReader(fileReader)) {
             
Такая конструкция называется try-with-resources, она позволяет автоматически освобождать занятые ресурсы при возникновении исключения в блоке. Как понять, что нужно ее использовать - классы имплементируют интерфейс Closeable/AutoCloseable

https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
https://javarush.ru/quests/lectures/questsyntaxpro.level15.lecture00

2022-05-18 10:10 UTC, mv-shallow commented on src/com/dasha/getCards/GetCardsFromTxt.java
> +    private List<String> getSubstringList(String readLine) {
Можно проще:         return Arrays.stream(readLine.split(",")).map(String::trim).toList();

2022-05-18 10:10 UTC, mv-shallow commented on src/com/dasha/PostMap.java
> +    public Map<UUID, Post> posts = new HashMap<>();
Инкапсулируй posts(доступ через проперти get/set)

2022-05-18 10:10 UTC, mv-shallow commented on src/com/dasha/getCards/GetCardsFromTxt.java
> +                employee.setPost((Post)map.posts.get(UUID.fromString(getSubstring(bufferedReader.readLine()))));
Явное преобразование к Post не нужно

2022-05-18 10:14 UTC, mv-shallow commented on src/com/dasha/Employee.java
> +        try{
А сам метод вполне можно заменить на переопределенный toString

2022-05-18 10:26 UTC, mv-shallow commented on src/com/dasha/printCards/PrintToConsole.java
> +        employees = employees.stream()
Сортировку можно упростить с помощью [Comparator](https://docs.oracle.com/javase/8/docs/api/java/util/Comparator.html#comparing-java.util.function.Function-)

В данном случае отдельный класс не нужен

2022-05-22 06:29 UTC, mv-shallow commented on src/com/dasha/Employee.java
> +        String b = "";
Лишнее?

2022-05-22 06:53 UTC, mv-shallow requested changes

2022-05-22 06:53 UTC, mv-shallow commented on src/com/dasha/printCards/PrintToConsole.java
> +            public int compare(Employee emp1, Employee emp2) {
Если сравнишь новый вариант и старый, то окажется, что новый даже сложнее... Я давал ссылку на метод comparing, с ним получится вполне лаконично

https://www.baeldung.com/java-8-comparator-comparing Разделы 3 и 6

2022-05-22 06:53 UTC, mv-shallow commented on src/com/dasha/Main.java
> +            return;
Лучше кинуть исключение (как вариант - RuntimeException или IllegalArgumentException с сообщением), потому что мы предполагаем работу с файлом. return в этом случае не нужен

2022-05-22 08:33 UTC, mv-shallow commented on src/com/dasha/Main.java
> +            throw new IllegalArgumentException("I can't find this file");
не предоставили путь к файлу

2022-05-22 08:39 UTC, mv-shallow commented
В сообщении к коммиту стоит писать что-то более осмысленное, тогда по истории коммитов можно получить представление о развитии проекта/ найти нужное изменение по названию коммита. Если изменения слишком разрозненные, но при этом небольшие, как сейчас, то можно написать просто "refactoring".

Чтобы лучше писать сообщения к коммитам можно посмотреть на историю крупных проектов.
Пример: https://github.com/mullvad/mullvadvpn-app/commits/master

![image](https://user-images.githubusercontent.com/62831519/169685998-d08f437a-7732-4557-9f14-f98c633fcf60.png)

2022-05-23 01:08 UTC, mv-shallow approved these changes

2022-05-23 01:09 UTC, mv-shallow commented
Я заапрувил, но сливать пока рано. Нужно дождаться ревью от сотрудника, указанного в таблице

2022-05-24 00:41 UTC, DGlobus commented
@mv-shallow, спасибо Вам за полезные советы и подсказки, как улучшить :)

2022-05-28 01:45 UTC, progressicu approved these changes

2022-05-28 01:45 UTC, progressicu commented on src/com/dasha/Employee.java
> +    String firstName;
private поля

2022-05-28 11:54 UTC, merged