Tests and search
DGlobus/baseballCards pull request #2
Opened 2022-06-04 06:59 UTC by DGlobus

2022-06-09 06:27 UTC, mv-shallow requested changes

2022-06-09 06:27 UTC, mv-shallow commented on src/main/java/com/dasha/Main.java
> +        //ParseEmployeeFile getCards = new ParseEmployeeTxt();
ПР без подобных комментариев

2022-06-09 06:27 UTC, mv-shallow commented on src/main/java/com/dasha/Main.java
> +        ParseEmployeeFile getCards= new ParseEmployeeJson();
Можно сделать полем класса и сразу инициализировать

2022-06-09 06:27 UTC, mv-shallow commented on src/main/java/com/dasha/model/Post.java
> +    public Post(UUID id, String name){
AllArgsConstructor вместо этого

2022-06-09 06:27 UTC, mv-shallow commented on src/main/java/com/dasha/model/PostMap.java
>      public PostMap(){
Лучше сделать метод fill и вызывать его после создания экземпляра(аннотация PostConstruct)

2022-06-09 06:27 UTC, mv-shallow commented on src/main/java/com/dasha/service/EmployeeService/EmployeeService.java
> +                .sorted((emp1, emp2)->  employeeComparator.compare(emp1, emp2))
Можно проще, компаратор ведь уже есть

2022-06-09 06:27 UTC, mv-shallow commented on src/main/java/com/dasha/service/getCards/EmployeeDTO.java
> +    private String firstName;
Не хватает валидации. Можно использовать NonNull из Lombok

2022-06-09 06:27 UTC, mv-shallow commented on src/main/java/com/dasha/service/getCards/ParseEmployeeJson.java
> +public class ParseEmployeeJson implements ParseEmployeeFile {
Методы класса вполне можно сделать статическими, а поля здесь не нужны, т.к. в хранении данных смысла нет. Тогда не придется инстанцировать класс(создавать его)

2022-06-09 06:27 UTC, mv-shallow commented on src/test/java/test/java/ParseEmployeeJsonTest.java
> +        employees.add(Employee.builder()
Лишние тестовые данные. Достаточно одной записи и двух тестов(когда все ок и когда есть ошибка - не хватает поля в json-е)

2022-06-09 06:27 UTC, mv-shallow commented on src/test/java/test/java/EmployeeServiceTest.java
> +        EmployeeService employeeService = new EmployeeService();
Везде встречается сервис, его стоит вынести в поле класса

2022-06-09 06:27 UTC, mv-shallow commented on src/main/java/com/dasha/service/EmployeeService/EmployeeService.java
> +
Не хватает хранения сотрудников

2022-06-09 06:27 UTC, mv-shallow commented on src/main/java/com/dasha/service/EmployeeService/EmployeeService.java
> +        List<Employee> changed = new ArrayList<>(employees);
Лишняя аллокация.

2022-06-09 06:27 UTC, mv-shallow commented on src/main/java/com/dasha/action/FromDtoToEmployee.java
> +public class FromDtoToEmployee {
Посмотри в сторону [mapstruct](https://www.baeldung.com/mapstruct), он как раз для этих целей.
Лучше не создавать лишний раз PostMap, а передавать в метод уже найденную должность. И метод стоит назвать не parse, а toEmployee или mapToEmployee, т.к. происходит отображение из класса в другой класс

2022-06-09 06:27 UTC, mv-shallow commented on src/main/java/com/dasha/service/EmployeeService/EmployeeService.java
> +    private boolean employeeContainsName(String searchParametr, String employeeParam){
Хороший подход, в будущем подобная конструкция пригодится для написания опционального фильтра(когда будет работа с базой)

2022-06-09 06:27 UTC, mv-shallow commented on src/test/java/test/java/ParseEmployeeJsonTest.java
> +        //arrange
Если подготовки нет, то не нужно писать блок. Между блоками лучше оставлять пустую строку, так нагляднее

2022-06-09 06:27 UTC, mv-shallow commented on src/main/java/com/dasha/Main.java
>          PrintToConsole print= new PrintToConsole(employees);
Если создаешь интерфейс, то лучше его где-нибудь применить. Можно здесь вместо класса указать его в левой части выражения

2022-06-09 06:27 UTC, mv-shallow commented on pom.xml
> +            <groupId>org.mockito</groupId>
Не увидел в тестах использование библиотеки

2022-06-09 06:32 UTC, mv-shallow commented
Пакеты не называют в camelCase: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

Из PostMap стоит сделать PostService, покскольку позже Post будет сущностью в базе данных

Классы для ввода-вывода не относятся к слою сервисов, их можно закинуть в какой-нибудь пакет под названием "ioutils"

2022-06-10 03:20 UTC, DGlobus commented
@mv-shallow, Добрый день, я недавно закончила задание по Spring и, соответственно, этот ПР уже не совсем актуален. Я постаралась учесть все Ваши замечания в новом задании, этот ПР стоит закрыть?

2022-06-10 13:08 UTC, mv-shallow commented
> @mv-shallow, Добрый день, я недавно закончила задание по Spring и, соответственно, этот ПР уже не совсем актуален. Я постаралась учесть все Ваши замечания в новом задании, этот ПР стоит закрыть?

В таком случае да, этот ПР можно закрыть

2022-06-11 07:21 UTC, progressicu commented on src/main/java/com/dasha/Main.java
> +            return null;
лучше возвращать не null, а пустой оъект

2022-06-11 07:21 UTC, progressicu commented on src/main/java/com/dasha/model/PostMap.java
>      public PostMap(){
здесь без спринга, так что так не получится. А в будущем да, было бы хорошо.
Сейчас можно просто создать такой метод и вызыывать сразу после создания

2022-06-11 07:22 UTC, mv-shallow commented on src/main/java/com/dasha/service/EmployeeService/EmployeeService.java
> +        List<Employee> changed = new ArrayList<>(employees);
Поскольку в стримах всё равно будет копирование входного списка: https://www.baeldung.com/java-copy-list-to-another (раздел 6)

2022-06-11 17:26 UTC, closed without merging