Add spring, controllers, exceptions, new models, refactor code
DGlobus/baseballCards pull request #3
Opened 2022-06-10 03:11 UTC by DGlobus

2022-06-10 04:38 UTC, snusmum commented on baseballCards.iml
> -  <component name="NewModuleRootManager" LANGUAGE_LEVEL="JDK_X">
Этот файл тоже не должен попадать в репозиторий

2022-06-10 07:45 UTC, snusmum requested changes
Просьба у комментариев помечать (ответом или иконкой), которые будут взяты в работу.
Если что-то остаётся как есть, то необходимо прокомментировать.

2022-06-10 07:45 UTC, snusmum commented on src/main/java/com/dasha/controller/employee/EmployeeController.java
> +    private final EmployeeService employeeService;
В качестве типа переменной необходимо использовать интерфейс, а не класс, который его реализует.

2022-06-10 07:45 UTC, snusmum commented on src/main/java/com/dasha/service/employee/EmployeeListService.java
> +@Service
Такие лучще создавать руками в конструкторе сервиса, в котором используется, т.к. он не зависит от контекста приложения (не требует подгрузки других бинов или переменных), чтобы экономить ресурсы.

2022-06-10 07:45 UTC, snusmum commented on src/main/java/com/dasha/service/employee/EmployeeService.java
> +    private final Map<UUID, Employee> employees;
Спринг конечно умный и не свалится с ошибкой, а создаст таки мапу.
Но лучше не доверять ему такое важное дело и создать то, что требуется руками.

2022-06-10 07:45 UTC, snusmum commented on src/main/java/com/dasha/service/employee/EmployeeService.java
> +        Employee updateEmployee = createEmployee(params);
В будущем нужно будет обновлять поля в существующей сущности, а не заменять её. Если есть возможность, то лучше сейчас поменять логику.

2022-06-10 07:45 UTC, snusmum commented on src/test/java/com/dasha/EmployeeServiceTest.java
> +public class EmployeeServiceTest {
EmployeeListServiceTest

2022-06-10 07:45 UTC, snusmum commented on src/test/java/com/dasha/EmployeeServiceTest.java
> +    private final PostService map = new PostService();
В юнит-тестах нельзя завязываться на логику других классов.
Исключение - утилитарные классы со статическими методами. В этом случае тест вынужден заодно покрывать и логику вызываемого метода (PowerMock не предлагать).

То, что сервис должностей хранит значения - это временно.

В данном случае нужно создавать должности, которые помещаются в тесовых сотрудников.

2022-06-10 07:45 UTC, snusmum commented on src/test/java/com/dasha/EmployeeServiceTest.java
> +        List<Employee> expected = List.of(Ivan, Petr);
В простых ситуациях нет необходимости в отдельных переменных. Удаление Сэкономит 2 строчки, а тест останется чистым и понятным.

2022-06-10 07:45 UTC, snusmum commented on src/test/java/com/dasha/test/controller/EmployeeControllerTest.java
> +public class EmployeeControllerTest {
Обычно интеграционные тесты называют по-другому (*IT или *IntegrationTest), чтобы они не гонялись вместе с юнит-тестами при сборке.
Но сейчас исправлять не требуется.

2022-06-10 07:45 UTC, snusmum commented on src/test/java/com/dasha/test/controller/EmployeeControllerTest.java
> +        checkEquals(createDto, employeeDto);
Если подключить AssertJ, то можно будет сравнивать объекты разных классов, совпадающие по полям.
Сейчас не обязательно.

2022-06-10 07:45 UTC, snusmum commented on src/test/java/com/dasha/test/controller/EmployeeControllerTest.java
> +        checkEquals(createDto, employeeDto);
Также в интеграционных тестах создания/обновления принято проверять, не только, что вернулись ожидаемые данные, но и что они появились в хранилище.

2022-06-10 07:45 UTC, snusmum commented on src/test/java/com/dasha/test/controller/EmployeeControllerTest.java
> +    void create() {
Планируются ли тесты остальных методов?

2022-06-10 07:45 UTC, snusmum commented on src/test/java/com/dasha/EmployeeServiceTest.java
> +public class EmployeeServiceTest {
Планируются ли тесты для  EmployeeService?

2022-07-05 14:19 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/EmployeeController.java
> +        return employeeService.getAll(param).stream().map(mapper::toDto).collect(Collectors.toList());
поправила

2022-07-05 14:23 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/dto/CreateEmployeeDto.java
> +    private String jobType;
Я рассудила, что модель заполняется данными из параметров, на них я поставила аннотации, поэтому не поставила проверок на модель

2022-07-05 14:24 UTC, DGlobus commented on src/main/java/com/dasha/exceptions/exception/ItemNotFoundException.java
> +@ResponseStatus(HttpStatus.NOT_FOUND)
В многочисленных попытках разобраться с тестами был какой-то прогресс с этой аннотацией и не работал без нее. Перестроила тест, аннотация стала ненужна

2022-07-05 14:25 UTC, DGlobus commented on src/main/java/com/dasha/service/ModelService.java
> +    T create(ParamT createParams);
Удалила данных интерфейс

2022-07-05 14:26 UTC, DGlobus commented on src/main/java/com/dasha/service/employee/EmployeeService.java
> +        Employee updateEmployee = createEmployee(params);
Поправила

2022-07-05 14:26 UTC, DGlobus commented on src/main/java/com/dasha/util/ioutils/parse/ParseEmployeeJson.java
> +                                .build();
Поправила

2022-07-05 14:29 UTC, DGlobus commented on src/test/java/com/dasha/test/controller/EmployeeControllerTest.java
> +        checkEquals(createDto, employeeDto);
Проверку добавления добавлю, когда начну работать с хранилищем

2022-07-05 14:30 UTC, DGlobus commented on src/test/java/com/dasha/test/controller/EmployeeControllerTest.java
> +public class EmployeeControllerTest {
Поправила

2022-07-06 02:15 UTC, snusmum commented on pom.xml
> +            <version>2.7.0</version>
Обычно версию не ставят. Используется та, что прописана в <parent>

2022-07-06 03:24 UTC, snusmum requested changes

2022-07-06 03:24 UTC, snusmum commented on src/main/java/com/dasha/service/employee/EmployeeService.java
> +        action.update(updateEmployee, params);
В аргументе должно приходить всё необходимое. Дальше прямо в сервисе значения подставляются в найденную сущность.
Причём обычно ставится всё то, что пришло, а не отбрасываются null-значения, если они допустимы. А если не допустимы, то это должно обрабатываться проверками в дто, аргументах.

2022-07-06 03:24 UTC, snusmum commented on src/main/java/com/dasha/service/employee/EmployeeService.java
> +        }
Вообще говоря, со спрингом все эти заморочки не нужны: в дто у параметра jobType указывается тип JobType и дальше невалидные значения не пройдут.
Причём так делать привильнее, когда проектируешь своё API, чем допускать произвольный текст, который придётся руками приводить к чему-то нужному.

2022-07-06 03:24 UTC, snusmum commented on src/main/java/com/dasha/service/employee/params/UpdateEmployeeParams.java
> +@Data
Тогда уж сразу `@Value`. Обычно аргументы делают неизменяемыми.

2022-07-06 03:24 UTC, snusmum commented on src/main/java/com/dasha/util/ioutils/parse/ParseEmployeeJson.java
>  public class ParseEmployeeJson implements ParseEmployeeFile {
Тоже уже не вызывается нигде, кроме тестов.

2022-07-06 03:24 UTC, snusmum commented on src/test/java/com/dasha/EmployeeListServiceTest.java
> +    private final PostService map = new PostService();
Повтор коммента, добавленного до переименования класса:

В юнит-тестах нельзя завязываться на логику других классов.
Исключение - утилитарные классы со статическими методами. В этом случае тест вынужден заодно покрывать и логику вызываемого метода (PowerMock не предлагать).

То, что сервис должностей хранит значения - это временно.

В данном случае нужно создавать должности, которые помещаются в тесовых сотрудников.

2022-07-06 03:24 UTC, snusmum commented on src/test/java/com/dasha/EmployeeListServiceTest.java
> +public class EmployeeListServiceTest {
Тесты EmployeeService всё ещё планируются?

2022-07-06 03:24 UTC, snusmum commented on src/test/java/com/dasha/test/controller/EmployeeControllerTest.java
> +public class EmployeeControllerTest {
Вроде ничего не поменялось относительно именования. Но и не обязательно.

2022-07-06 03:24 UTC, snusmum commented on src/test/java/com/dasha/test/controller/EmployeeControllerTest.java
> +    private final EmployeeMapper mapper = new EmployeeMapperImpl();
Тест интеграционный. При прогоне поднимается контекст и создаются бины. @Authowired позволяет заинжектить их в данный класс.
Руками создавать экземпляры не нужно.

2022-07-06 03:24 UTC, snusmum commented on src/test/java/com/dasha/test/controller/EmployeeControllerTest.java
> +        );
В дто лучше не добавлять открытый конструктор со всеми аргументами, чтобы не было соблазна его использовать.
Нужно создавать пустой объект и заполнять сеттерами только нужные поля.
Ну, или, таки вернуть билдер и использовать его.

2022-07-06 13:27 UTC, DGlobus commented on pom.xml
> +            <version>2.7.0</version>
поправила

2022-07-06 13:29 UTC, DGlobus commented on src/main/java/com/dasha/action/AddEmployeeFromFile.java
> +        List<Employee> employees = new ArrayList<>();
добавила в контроллер метод, принимающий файл и добавляющий сотрудников из него

2022-07-06 13:29 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/EmployeeController.java
> +    @PostMapping("/getAll/sorted")
Поправила

2022-07-06 13:29 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/EmployeeController.java
>      }
Поправила

2022-07-06 13:29 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/dto/CreateEmployeeDto.java
> +    private Post post;
Поправила

2022-07-06 13:30 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/EmployeeController.java
>      @PostMapping("/update/{id}")
Поправила

2022-07-06 13:30 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/EmployeeController.java
> +        Employee newEmp = employeeService.update(dto.getId(), mapper.toParams(dto));
Поправила

2022-07-06 13:30 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/mapper/EmployeeMapper.java
> +    })
Поправила

2022-07-06 13:30 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/EmployeeController.java
>      @PostMapping("/getById/{id}")
Поправила

2022-07-06 13:30 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/EmployeeController.java
>      }
Поправила

2022-07-06 13:31 UTC, DGlobus commented on src/main/java/com/dasha/service/employee/EmployeeService.java
>          }
Убрала

2022-07-06 13:32 UTC, DGlobus commented on src/main/java/com/dasha/service/employee/EmployeeService.java
> +        action.update(updateEmployee, params);
Изменила

2022-07-06 13:32 UTC, DGlobus commented on src/main/java/com/dasha/service/employee/EmployeeService.java
> +        }
Убрала строковые значения для JobType

2022-07-06 13:34 UTC, DGlobus commented on src/test/java/com/dasha/EmployeeListServiceTest.java
> +public class EmployeeListServiceTest {
Добавила тесты

2022-07-06 13:34 UTC, DGlobus commented on src/test/java/com/dasha/test/controller/EmployeeControllerTest.java
> +    private final EmployeeMapper mapper = new EmployeeMapperImpl();
Поправила

2022-07-06 13:34 UTC, DGlobus commented on src/test/java/com/dasha/test/controller/EmployeeControllerTest.java
> +        );
Поправила

2022-07-07 03:30 UTC, snusmum requested changes

2022-07-07 03:30 UTC, snusmum commented on src/main/java/com/dasha/controller/employee/EmployeeController.java
> +    public List<EmployeeDto> createFromFile(@RequestBody File file){
Можно оставить метод и для порядка переименовать в createFromLocalFile, и хвост поправить.
Для загрузки произвольного файла нужно использовать MultipartFile (https://spring.io/guides/gs/uploading-files/)

2022-07-07 03:30 UTC, snusmum commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        assertThat(actual).usingRecursiveComparison().ignoringFields("id", "post").isEqualTo(expected);
Если что-то исключили, то надо бы отдельно проверить.
id - что не null, post - какая должна быть.

2022-07-07 03:30 UTC, snusmum commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        assertThat(actual).usingRecursiveComparison().ignoringFields("id", "post", "contacts").isEqualTo(expected);
Тоже нужно все поля, которые содержат не генерируемые значения нужно проверять.

2022-07-07 03:30 UTC, snusmum commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        expected.setDescription(null);
В интеграционном тесте обновления нужно менять все возможные поля, чтобы убедиться, что никакое из них не забыто.

2022-07-07 03:30 UTC, snusmum commented on src/test/java/com/dasha/service/EmployeeServiceTest.java
> +        assertThat(actual).usingRecursiveComparison().ignoringFields("id").isEqualTo(expected);
Получается, что тест проверяет то, что вернулось из сервиса, но не то что сохранилось.
В таких ситуациях также можно пользоваться рефлексией, чтобы вытянуть значения.
Другие варианты: 
- если разрабатывать по TDD, то, скорее всего, были бы добавлены packagePrivate методы для работы с хранилищем (ещё исключение про методы ради тестов)
- унести хранилище из сервиса, т.е. сделать аналог репозитория.

2022-07-07 09:57 UTC, DGlobus commented on src/main/java/com/dasha/action/AddEmployeeFromFile.java
> +            CreateEmployeeDto dto = mapper.toDto(emp);
Изменила

2022-07-07 09:57 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/EmployeeController.java
> +        return mapper.toDto(updateAction.update(id, dto));
Поправила

2022-07-07 09:57 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/EmployeeController.java
> +                                     @RequestParam boolean isSorting){
Поправила

2022-07-07 09:57 UTC, DGlobus commented on src/main/java/com/dasha/action/UpdateAction.java
> +        if(dto.getPostId() != null) params.setPost(postService.getById(dto.getPostId()));
Поправила

2022-07-07 09:58 UTC, DGlobus commented on src/main/java/com/dasha/service/employee/params/UpdateEmployeeParams.java
> +@Data
В действии обновления сотрудника проставляется сущность должности, так что не получается его пока сделать неизменяемым

2022-07-07 09:59 UTC, DGlobus commented on src/main/java/com/dasha/util/Guard.java
> +    }
В задании было сказано создать исключение и с ним поработать, а здесь я выбрала бросать RuntimeException, но на будущее оставила

2022-07-07 10:00 UTC, DGlobus commented on src/main/java/com/dasha/config/SwaggerConfig.java
> + * @author Maxim Seredkin
Убрала

2022-07-07 10:01 UTC, DGlobus commented on src/main/java/com/dasha/config/SwaggerConfig.java
> +public class SwaggerConfig {
Добавила аннотации

2022-07-07 10:01 UTC, DGlobus commented on src/main/java/com/dasha/service/post/PostService.java
> +        fill(); //for test
Поправила

2022-07-07 10:02 UTC, DGlobus commented on src/main/java/com/dasha/util/ioutils/print/PrintCards.java
> +package com.dasha.util.ioutils.print;
Стоит удалить эти классы?

2022-07-07 10:02 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/EmployeeController.java
> +    public List<EmployeeDto> createFromFile(@RequestBody File file){
Переименовала метод и хвост

2022-07-07 10:02 UTC, DGlobus commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        assertThat(actual).usingRecursiveComparison().ignoringFields("id", "post").isEqualTo(expected);
Добавила проверки

2022-07-07 10:03 UTC, DGlobus commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        EmployeeDto expected = createEmployeeInService(vasya);
Изменила логику

2022-07-07 10:03 UTC, DGlobus commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        expected.setDescription(null);
Поправила

2022-07-08 01:13 UTC, snusmum approved these changes
В целом хорошо. Пройдись ещё раз по комментам. Есть что поправить.
Что не будет исправлено нужно будет менять уже в следующем ПР.

2022-07-08 01:13 UTC, snusmum commented on src/test/java/com/dasha/ParseEmployeeJsonTest.java
> +package com.dasha;
Все тесты нужно помещать в такие же пакеты, как и тестируемые классы. Если делать структуру отличной, то с ней потом тяжелее работать.
Кроме того, это позволит работать с package private полями и методами.

2022-07-08 01:13 UTC, snusmum commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        }
`ReflectionTestUtils.setField(employeeService, "employees", map);` под капотом примерно тоже самое делает.

2022-07-08 01:13 UTC, snusmum commented on src/test/java/com/dasha/service/PostServiceTest.java
> +        }
Тоже можно одной строчкой вызывать.

2022-07-08 02:39 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/dto/ContactsDto.java
> +    @ApiModelProperty(name = "Номер телефона")
Добавила

2022-07-08 02:40 UTC, DGlobus commented on src/main/java/com/dasha/service/post/PostService.java
> +    public Post update(@NotNull UUID postId, CreatePostParams params) {
Добавила UpdatePostDto

2022-07-08 02:40 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/EmployeeController.java
> +        params.setId(id);
Поправила

2022-07-08 02:40 UTC, DGlobus commented on src/main/java/com/dasha/action/UpdateAction.java
> +public class UpdateAction {
Изменила

2022-07-08 02:41 UTC, DGlobus commented on src/main/java/com/dasha/util/Guard.java
> +    }
Создала

2022-07-08 02:41 UTC, DGlobus commented on src/main/java/com/dasha/util/ioutils/parse/ParseEmployeeTxt.java
> +public class ParseEmployeeTxt implements ParseEmployeeFile {
Удалила

2022-07-08 02:42 UTC, DGlobus commented on src/main/java/com/dasha/controller/employee/mapper/EmployeeMapper.java
> +    @Mapping(target = "post.id", source = "dto.postId")
Добавила параметры обновления для сервиса

2022-07-08 02:42 UTC, DGlobus commented on src/test/java/com/dasha/ParseEmployeeJsonTest.java
> +package com.dasha;
Поправила

2022-07-08 02:43 UTC, DGlobus commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        }
Поправила

2022-07-08 02:43 UTC, DGlobus commented on pom.xml
> +            <version>${parent.version}</version>
Убрала

2022-07-11 04:03 UTC, merged