added post and employee repositories, added logging, changed tests
DGlobus/baseballCards pull request #4
Opened 2022-07-25 06:05 UTC by DGlobus

2022-07-27 07:51 UTC, snusmum requested changes
Необходимо добавить аспектам юнит-тесты.

Под * можно в интеграционных тестах контроллера проверить запись в лог, перехватив сообщения логгеру.

2022-07-27 07:51 UTC, snusmum commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        postRepository.save(student);
Вместо заполнения базы руками лучше воспользоваться функционалом [Database Rider](https://database-rider.github.io/getting-started/), подтягиваемым вместе с `spring-test-postgres`: `@DataSet("post.json")`
Можно и yml вместо json, но не везде он приижвается.

2022-07-27 07:51 UTC, snusmum commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        employeeRepository.deleteAll();
И это не потребуется.

2022-07-27 07:51 UTC, snusmum commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        assertTrue(employeeRepository.existsById(actual.getId()));
Пользуясь `@ExpectedDataSet` можно также удобно проверять изменения в базе.

2022-07-27 07:51 UTC, snusmum commented on src/test/resources/cards.json
> +    "description": "Big Harry Potter Fan",
😄 What about LOTR?

2022-07-27 07:51 UTC, snusmum commented on src/main/java/com/dasha/util/logging/ApiLogging.java
> +package com.dasha.util.logging;
Обычно аспектам и всему, что с ними связано выделяют свой пакет на верхнем уровне. Но не принципиально.

2022-07-27 07:51 UTC, snusmum commented on src/main/java/com/dasha/service/post/PostService.java
>          return post;
Правильнее будет ответ репозитория возвращать, на случай использования, например `@PrePersist`.

2022-07-27 22:49 UTC, snusmum commented on src/main/java/com/dasha/util/logging/LoggingControllers.java
> +    public void recordItemNotFoundException(JoinPoint joinPoint, Throwable e) {
Этого не было в задании

2022-07-27 22:50 UTC, snusmum commented on src/main/java/com/dasha/util/logging/LoggingControllers.java
> +    @Around(value = "loggingControllerPointcut()")
Хватило бы Before.

2022-07-28 02:44 UTC, snusmum commented on src/main/java/com/dasha/action/CreateEmployeeAction.java
> +    public Employee create(CreateEmployeeParams params) {
Раз все сущности теперь тянутся из базы, то работать с ними (доставать, вкладывать, сохранять) нужно в рамках одной транзакции, чтобы в случае параллельного изменения одной из них (вдруг кто-то должность переименовал) сотрудник не обновился.
Для этого методы действий нужно завернуть в Transactional.

2022-07-29 01:16 UTC, DGlobus commented on src/main/java/com/dasha/model/Employee.java
> +@RequiredArgsConstructor
Поправила

2022-07-29 01:17 UTC, DGlobus commented on src/main/java/com/dasha/service/employee/EmployeeService.java
> +        return repository.findById(employeeId).orElse(null);
Поправила

2022-07-29 01:17 UTC, DGlobus commented on src/main/java/com/dasha/service/employee/EmployeeService.java
> +        List<Employee> list = new ArrayList<>(repository.findAll());
изменила

2022-07-29 01:17 UTC, DGlobus commented on src/main/java/com/dasha/util/logging/LoggingControllers.java
> +    @Pointcut("@annotation(ApiLogging)")
изменила

2022-07-29 01:19 UTC, DGlobus commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        postRepository.save(student);
Возникли проблемы с реализацией через DBRider, понадобится чуть больше времени, чтобы разобраться с ошибками. Пока оставила как было, планирую доработать в любом случае

2022-07-29 01:22 UTC, DGlobus commented on src/test/resources/cards.json
> +    "description": "Big Harry Potter Fan",
They are greate, but The Boy Who Lived has very special place in my heart :)))

2022-07-29 01:22 UTC, DGlobus commented on src/main/java/com/dasha/service/post/PostService.java
>          return post;
поправила

2022-07-29 01:23 UTC, DGlobus commented on src/main/java/com/dasha/action/CreateEmployeeAction.java
> +    public Employee create(CreateEmployeeParams params) {
поправила

2022-07-29 06:07 UTC, snusmum requested changes
Для юнит-тестов аспектов можно воспользоваться [этой](https://www.simplify4u.org/slf4j-mock/) библиотекой. Но нужно будет немного поправить тест + в pom придётся для тестов отключить logback через maven-surefire-plugin.

2022-07-29 06:07 UTC, snusmum commented on src/main/java/com/dasha/util/logging/AspectAppender.java
> +}
👍 Только нужно это в тестовые утили переместить.

2022-07-31 02:57 UTC, DGlobus commented on src/main/java/com/dasha/service/employee/EmployeeService.java
> +                                              : QEmployee.employee.firstName.contains(params.getName()));
Поправила

2022-07-31 02:57 UTC, DGlobus commented on src/test/java/com/dasha/service/EmployeeServiceTest.java
> +@EnablePostgresDataTest
Поменяла логику

2022-07-31 02:58 UTC, DGlobus commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +    void getAll() {
Добавила тесты на проверку с параметрами

2022-07-31 14:20 UTC, snusmum requested changes
Осталось сделать так, чтобы проходили все тесты.
Если заодно победишь DbRider будет супер.

2022-07-31 14:20 UTC, snusmum commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        if(loggingOn)
Обычно для тестов это включают или глобально в application.properties или через @TestPropertySource

2022-07-31 14:20 UTC, snusmum commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
А в целом тесты нормально рабботают? А если сделать mvn clean compile, а потом прогнать опять?

2022-07-31 14:20 UTC, snusmum commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        expected.remove(0);
Да. С DbRider жить явно проще.

2022-08-01 01:20 UTC, DGlobus commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        if(loggingOn)
Поправила

2022-08-01 01:21 UTC, DGlobus commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
Да, тесты работают и после mvn clean compile тоже

2022-08-01 01:22 UTC, DGlobus commented on src/test/java/com/dasha/controller/EmployeeControllerIT.java
> +        expected.remove(0);
Я постараюсь сегодня разобраться с этим

2022-08-01 01:58 UTC, snusmum approved these changes
Можно сливать.
Для дальнейшей работы DbRider точно понадобится, поэтому придётся разобраться.

2022-08-01 06:12 UTC, merged